### ISSUE TITLE
addimage appears not to work for new collections

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#121]
```
bot_1      | Traceback (most recent call last):
bot_1      |   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
bot_1      |     ret = await coro(*args, **kwargs)
bot_1      |   File "/usr/src/app/src/picturecommands.py", line 442, in add_image
bot_1      |     image_collection = self.get_cmd_from_alias(image_collection)
bot_1      |   File "/usr/src/app/src/picturecommands.py", line 379, in get_cmd_from_alias
bot_1      |     cursor.execute(
bot_1      |   File "/usr/local/lib/python3.8/site-packages/psycopg2/extras.py", line 243, in execute
bot_1      |     return super(RealDictCursor, self).execute(query, vars)
bot_1      | TypeError: not all arguments converted during string formatting
```

**Comment by makusu2** [comment]
Fixed, there were a bunch of issues.
