### ISSUE TITLE
Issue with mb.remindme with no date specified

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#195]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/src/app/src/reminders.py", line 183, in remind_me
    reminder_message = await util.clean(ctx, reminder_message)
  File "/usr/src/app/src/util.py", line 223, in clean
    return await converter.convert(ctx, s)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 531, in convert
    result = pattern.sub(repl, argument)
TypeError: expected string or bytes-like object
```

**Comment by makusu2** [comment]
At https://github.com/makusu2/makubot/blob/22bd635a61d723bde961cd3b5531c9003dcb1a67/src/reminders.py#L183, 
`reminder_message = await util.clean(ctx, reminder_message) if reminder_message else ""`
