### ISSUE TITLE
mb.help lupo (or any image command) breaks

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#207]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 860, in command_callback
    return await self.send_command_help(cmd)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1310, in send_command_help
    self.add_command_formatting(command)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1209, in add_command_formatting
    self.add_aliases_formatting(command.aliases)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1192, in add_aliases_formatting
    self.paginator.add_line('**%s** %s' % (self.aliases_heading, ', '.join(aliases)), empty=True)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 127, in add_line
    raise RuntimeError('Line exceeds maximum page size %s' % (max_page_size))
RuntimeError: Line exceeds maximum page size 1998

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: Line exceeds maximum page size 1998
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 860, in command_callback
    return await self.send_command_help(cmd)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1310, in send_command_help
    self.add_command_formatting(command)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1209, in add_command_formatting
    self.add_aliases_formatting(command.aliases)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 1192, in add_aliases_formatting
    self.paginator.add_line('**%s** %s' % (self.aliases_heading, ', '.join(aliases)), empty=True)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 127, in add_line
    raise RuntimeError('Line exceeds maximum page size %s' % (max_page_size))
RuntimeError: Line exceeds maximum page size 1998

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: Line exceeds maximum page size 1998
```

**Comment by makusu2** [comment]
One fix is:
```
    bot.get_command("send_image_func").update(
        help="Use this command to send an image from an image directory!",
        usage="",
    )
```
But for some reason, if you do that, mb.lupo (which accepts self and ctx) will only receive ctx. Why? I have no fucking idea.

Let's update the help function instead.

**Comment by makusu2** [comment]
If I do this:
```
    async def send_command_help(self, command):
        if command.callback.__name__ == "send_image_func":
            await self.get_destination().send(
                "Use this command to send an image from an image directory!")
        else:
            super(MyHelpCommand, self).send_command_help(command)
```
Any command but an image command sends no output, for some reason. Heck.

**Comment by makusu2** [comment]
Oh wait, it works, I just didn't await!
