### ISSUE TITLE
Fix emoji bug

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#219]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/src/app/src/picturecommands.py", line 559, in listreactions
    await util.displaytxt(ctx, pictures_desc)
  File "/usr/src/app/src/util.py", line 278, in displaytxt
    res = await ctx.bot.wait_for("reaction_add", check=check)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 339, in dispatch
    result = condition(*args)
  File "/usr/src/app/src/util.py", line 271, in check
    and reaction.emoji in button_emojis
TypeError: 'in <string>' requires string as left operand, not PartialEmoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'in <string>' requires string as left operand, not PartialEmoji
```

**Comment by makusu2** [comment]
I think this already got fixed, whoops
