### ISSUE TITLE
Investigate UnknownEmoji bug

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#230]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/src/app/src/fun.py", line 69, in emojispam
    await all_emoji_futures
  File "/usr/local/lib/python3.8/site-packages/discord/message.py", line 996, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
```

**Comment by makusu2** [comment]
Well Now It Is Not Doing It
Although this is aesthetic as fuck:
![image](https://user-images.githubusercontent.com/25968054/95004980-75042e00-05c0-11eb-942b-373a5910fa18.png)

**Comment by makusu2** [comment]
Alright, closing cuz it's not happening anymore
